name: OSINTify CI Pipeline

# When to trigger the workflow: on pushes to main or pull requests to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment for testing

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.9  # Choose the version you're using
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: (Optional) Run linting checks using flake8 for code quality
      - name: Lint code using flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Check Python version
        run: python --version

      - name: Check installed packages
        run: pip list
     

  google-dorking:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Perform Google Dorking on a sample domain (modify as needed)
      - name: Run Google Dorking example
        run: |
          python osint.py -d example.com  # Replace with actual command you use

  github-recon:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Perform GitHub Recon on a sample domain (modify as needed)
      - name: Run GitHub Recon example
        run: |
          python osint.py -d example.com  # Modify with the command you use

      
